//Products by MockApi (requests from Insonmia)
export const allProducts = [
  {
    manufacturer: "Aorus",
    price: 280.9,
    image: "/assets/products/placaAorus.svg",
    description: "Placa-mãe Gigabyte Aorus B450 Aorus M, AMD AM4, mATX, DDR4",
    shipping: true,
    old_price: 380.9,
    id: "1",
  },
  {
    manufacturer: "AMD",
    price: 800.9,
    image: "/assets/products/ryzen.svg",
    description: "Processador AMD Ryzen 7 3800X Cache 32MB 3.9GHz 4.5GHz Max",
    shipping: false,
    old_price: 900.5,
    id: "2",
  },
  {
    manufacturer: "Hyperx",
    price: 400,
    image: "/assets/products/memory.svg",
    description: "Memória HyperX Fury, 8GB, 2400MHz, DDR4, CL15, Preto...",
    shipping: true,
    old_price: 299.5,
    id: "3",
  },
  {
    manufacturer: "Hyperx",
    price: 280,
    image: "/assets/products/headset.svg",
    description: "Headset Gamer HyperX Cloud Stinger - HX-HSCS-BK/NA",
    shipping: false,
    old_price: 389.5,
    id: "4",
  },
  {
    manufacturer: "Amazon",
    price: 280,
    image: "/assets/products/alexa.svg",
    description: "Amazon Smart Home Echo Dot Alexa, 3ª Geração, Preto",
    shipping: true,
    old_price: 480.5,
    id: "5",
  },
];
